apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage-pvc
  namespace: mlops-poc
spec:
  accessModes:
    - ReadWriteOnce  # Single server, local storage
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
