apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: mlops-poc
type: Opaque
stringData:
  # MinIO root credentials
  root-user: "<minio_root_user>"
  root-password: "<minio_root_password>"

  # AWS-compatible credentials for S3 clients
  access-key: "<minio_access_key>"
  secret-key: "<minio_secret_key>"
