name: rps
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - scipy=1.11.4
  - seaborn=0.13.2
  - joblib
  - pip
  - pip:
      - mlflow==2.8.1
      - xgboost==2.0.3
      - torch==2.5.1 --extra-index-url https://download.pytorch.org/whl/cpu
      - torchvision==0.20.1 --extra-index-url https://download.pytorch.org/whl/cpu
      - cloudpickle==2.2.1
      - pyarrow==14.0.2
      - tqdm==4.67.1
      - fastapi==0.110.0
      - uvicorn[standard]==0.29.0
      - prometheus-fastapi-instrumentator==6.1.0
      - pydantic==2.11.7
      - jinja2==3.1.4
  - httpx==0.25.2
