[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rps"
version = "0.0.1"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["trainer", "trainer.*"]
