apiVersion: v1
kind: Secret
metadata:
  name: external-creds
  namespace: mlops-poc
type: Opaque
stringData:
  # Grafana Cloud remote_write basic auth or API key. If using username/password, format as below.
  GRAFANA_USERNAME: "<your_prom_user_or_id>"
  GRAFANA_PASSWORD: "<your_prom_password_or_api_key>"
  # DagsHub / MLflow (optional for later)
  MLFLOW_TRACKING_URI: "https://dagshub.com/<user>/<repo>.mlflow"
  MLFLOW_TRACKING_USERNAME: "<dagshub_username>"
  MLFLOW_TRACKING_PASSWORD: "<dagshub_token>"