apiVersion: v1
kind: Service
metadata:
  name: rps-app
  namespace: mlops-poc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector: { app: rps-app }
  ports:
  - name: web
    port: 80
    targetPort: 8080
